Tunnel_container_scanning:
  stage: test
  image:
    name: alpine:3.11
  variables:
    # Override the GIT_STRATEGY variable in your `.gitlab-ci.yml` file and set it to `fetch` if you want to provide a `clair-whitelist.yml`
    # file. See https://docs.gitlab.com/ee/user/application_security/container_scanning/index.html#overriding-the-container-scanning-template
    # for details
    GIT_STRATEGY: none
    IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  allow_failure: true
  before_script:
    - export TUNNEL_VERSION=${TUNNEL_VERSION:-v0.19.2}
    - apk add --no-cache curl docker-cli
    - curl -sfL https://raw.githubusercontent.com/khulnasoft/tunnel/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${TUNNEL_VERSION}
    - curl -sSL -o /tmp/tunnel-gitlab.tpl https://github.com/khulnasoft/tunnel/raw/${TUNNEL_VERSION}/contrib/gitlab.tpl
    - tunnel registry login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - tunnel --exit-code 0 --cache-dir .tunnelcache/ --no-progress --format template --template "@/tmp/tunnel-gitlab.tpl" -o gl-container-scanning-report.json $IMAGE
  cache:
    paths:
      - .tunnelcache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  dependencies: []
  only:
    refs:
      - branches
