// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"go.khulnasoft.com/tunnel-db/pkg/db"
	"github.com/khulnasoft/tunnel/pkg/cache"
	"github.com/khulnasoft/tunnel/pkg/fanal/applier"
	"github.com/khulnasoft/tunnel/pkg/scanner/langpkg"
	"github.com/khulnasoft/tunnel/pkg/scanner/local"
	"github.com/khulnasoft/tunnel/pkg/scanner/ospkg"
	"github.com/khulnasoft/tunnel/pkg/vulnerability"
)

// Injectors from inject.go:

func initializeScanServer(localArtifactCache cache.LocalArtifactCache) *ScanServer {
	applierApplier := applier.NewApplier(localArtifactCache)
	scanner := ospkg.NewScanner()
	langpkgScanner := langpkg.NewScanner()
	config := db.Config{}
	client := vulnerability.NewClient(config)
	localScanner := local.NewScanner(applierApplier, scanner, langpkgScanner, client)
	scanServer := NewScanServer(localScanner)
	return scanServer
}
