// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/khulnasoft-lab/tunnel-db/pkg/db"
	"github.com/khulnasoft/tunnel/pkg/cache"
	"github.com/khulnasoft/tunnel/pkg/fanal/applier"
	"github.com/khulnasoft/tunnel/pkg/scan/langpkg"
	"github.com/khulnasoft/tunnel/pkg/scan/local"
	"github.com/khulnasoft/tunnel/pkg/scan/ospkg"
	"github.com/khulnasoft/tunnel/pkg/vulnerability"
)

// Injectors from inject.go:

func initializeScanServer(localArtifactCache cache.LocalArtifactCache) *ScanServer {
	applierApplier := applier.NewApplier(localArtifactCache)
	scanner := ospkg.NewScanner()
	langpkgScanner := langpkg.NewScanner()
	config := db.Config{}
	client := vulnerability.NewClient(config)
	service := local.NewService(applierApplier, scanner, langpkgScanner, client)
	scanServer := NewScanServer(service)
	return scanServer
}
