{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tunnel.fullname" . }}
  labels:
{{ include "tunnel.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tunnel.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tunnel.fullname" . }}
{{- end }}