{{- if not .Values.tunnel.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tunnel.fullname" . }}
  labels:
{{ include "tunnel.labels" . | indent 4 }}
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.tunnel.gitHubToken | default "" | b64enc | quote }}
  TUNNEL_TOKEN: {{ .Values.tunnel.serverToken | default "" | b64enc | quote }}
{{- if not .Values.tunnel.registryCredentialsExistingSecret }}
  TUNNEL_USERNAME: {{ .Values.tunnel.registryUsername | default "" | b64enc | quote }}
  TUNNEL_PASSWORD: {{ .Values.tunnel.registryPassword | default "" | b64enc | quote }}
{{- end -}}
{{- end }}
