apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tunnel.fullname" . }}
  labels:
{{ include "tunnel.labels" . | indent 4 }}
{{- if (.Values.tunnel.serviceAccount).annotations }}
  annotations:
{{ toYaml .Values.tunnel.serviceAccount.annotations | indent 4 }}
{{- end }}
  namespace: {{ .Release.Namespace }}