apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "tunnel.fullname" .) }}
  labels:
{{ include "tunnel.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "tunnel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: tunnel-http
      protocol: TCP
      port: {{ .Values.service.port | default 4954 }}
      targetPort: {{ .Values.service.port | default 4954 }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "ClientIP" }}

