// Code generated by mockery v2.52.3. DO NOT EDIT.

package ospkg

import (
	context "context"

	types "github.com/khulnasoft/tunnel/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockScanner is an autogenerated mock type for the Scanner type
type MockScanner struct {
	mock.Mock
}

// Scan provides a mock function with given fields: ctx, target, options
func (_m *MockScanner) Scan(ctx context.Context, target types.ScanTarget, options types.ScanOptions) (types.Result, bool, error) {
	ret := _m.Called(ctx, target, options)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 types.Result
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ScanTarget, types.ScanOptions) (types.Result, bool, error)); ok {
		return rf(ctx, target, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ScanTarget, types.ScanOptions) types.Result); ok {
		r0 = rf(ctx, target, options)
	} else {
		r0 = ret.Get(0).(types.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ScanTarget, types.ScanOptions) bool); ok {
		r1 = rf(ctx, target, options)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, types.ScanTarget, types.ScanOptions) error); ok {
		r2 = rf(ctx, target, options)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockScanner creates a new instance of MockScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanner {
	mock := &MockScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
