name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tag push, like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'  # Specify the Go version

      # Step 3: Install GoReleaser
      - name: Install GoReleaser
        run: |
          curl -sSL https://github.com/goreleaser/goreleaser/releases/download/v1.14.0/goreleaser_Linux_x86_64.tar.gz | tar -xzv
          sudo mv goreleaser /usr/local/bin/

      # Step 4: Run GoReleaser
      - name: Run GoReleaser
        run: goreleaser release

      # Step 5: Upload release artifacts (optional)
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
